### ISSUE TITLE
index.html 파일 수정 부탁드립니다.

### ISSUE THREAD

**Issue by sigmadream** [Hhyeongju/ks-web#1]
index.html 파일을 과제에 있는 내용으로 수정 부탁드립니다.

**Comment by Hhyeongju** [comment]
파일을 수정하여 다시 업로드 했습니다!
확인 부탁드립니다!!
 
-----Original Message-----

**Comment by Hhyeongju** [comment]
새로 만들어서 다시 했는데 마지막에 push하는 과정이 안됩니다...
